export const icons = {
    Bug: require('../global/assets/Icons/Bug.png'),
    Grass: require('../global/assets/Icons/Grass.png'),
    Dragon: require('../global/assets/Icons/Dragon.png'),
    Electric: require('../global/assets/Icons/Electric.png'),
    Fairy: require('../global/assets/Icons/Fairy.png'),
    Fighting: require('../global/assets/Icons/Fighting.png'),
    Fire: require('../global/assets/Icons/Fire.png'),
    Ghost: require('../global/assets/Icons/Ghost.png'),
    Ice: require('../global/assets/Icons/Ice.png'),
    Normal: require('../global/assets/Icons/Normal.png'),
    Poison: require('../global/assets/Icons/Poison.png'),
    Psychic: require('../global/assets/Icons/Psychic.png'),
    Rock: require('../global/assets/Icons/Rock.png'),
    Steel: require('../global/assets/Icons/Steel.png'),
    Water: require('../global/assets/Icons/Water.png'),
    Ground: require('../global/assets/Icons/Ground.png'),
    Flying: require('../global/assets/Icons/Flying.png'),
}
